

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(563, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 250, 541, 311))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 341, 141))
        self.box_devices = QComboBox(self.groupBox)
        self.box_devices.setObjectName(u"box_devices")
        self.box_devices.setGeometry(QRect(50, 20, 141, 22))
        self.btn_refresh = QPushButton(self.groupBox)
        self.btn_refresh.setObjectName(u"btn_refresh")
        self.btn_refresh.setGeometry(QRect(10, 20, 31, 23))
        self.label_devices_info = QLabel(self.groupBox)
        self.label_devices_info.setObjectName(u"label_devices_info")
        self.label_devices_info.setGeometry(QRect(20, 60, 301, 61))
        self.btn_connect_device = QPushButton(self.groupBox)
        self.btn_connect_device.setObjectName(u"btn_connect_device")
        self.btn_connect_device.setGeometry(QRect(200, 20, 61, 23))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 160, 341, 81))
        self.btn_log_clear = QPushButton(self.groupBox_3)
        self.btn_log_clear.setObjectName(u"btn_log_clear")
        self.btn_log_clear.setGeometry(QRect(180, 20, 75, 23))
        self.box_log_level = QComboBox(self.groupBox_3)
        self.box_log_level.addItem("")
        self.box_log_level.addItem("")
        self.box_log_level.addItem("")
        self.box_log_level.addItem("")
        self.box_log_level.setObjectName(u"box_log_level")
        self.box_log_level.setGeometry(QRect(100, 20, 71, 22))
        self.label = QLabel(self.groupBox_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 61, 21))
        self.btn_log_start = QPushButton(self.groupBox_3)
        self.btn_log_start.setObjectName(u"btn_log_start")
        self.btn_log_start.setGeometry(QRect(260, 20, 75, 23))
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 50, 71, 21))
        self.box_log_save_path = QComboBox(self.groupBox_3)
        self.box_log_save_path.setObjectName(u"box_log_save_path")
        self.box_log_save_path.setGeometry(QRect(100, 50, 91, 22))
        self.btn_log_output = QPushButton(self.groupBox_3)
        self.btn_log_output.setObjectName(u"btn_log_output")
        self.btn_log_output.setGeometry(QRect(260, 50, 75, 23))
        self.btn_log_clear_file = QPushButton(self.groupBox_3)
        self.btn_log_clear_file.setObjectName(u"btn_log_clear_file")
        self.btn_log_clear_file.setGeometry(QRect(200, 50, 51, 23))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(360, 10, 191, 141))
        self.btn_screencap = QPushButton(self.groupBox_2)
        self.btn_screencap.setObjectName(u"btn_screencap")
        self.btn_screencap.setGeometry(QRect(10, 80, 81, 23))
        self.btn_record_start = QPushButton(self.groupBox_2)
        self.btn_record_start.setObjectName(u"btn_record_start")
        self.btn_record_start.setGeometry(QRect(10, 110, 81, 23))
        self.btn_screencap_clear_file = QPushButton(self.groupBox_2)
        self.btn_screencap_clear_file.setObjectName(u"btn_screencap_clear_file")
        self.btn_screencap_clear_file.setGeometry(QRect(100, 80, 81, 23))
        self.btn_record_output = QPushButton(self.groupBox_2)
        self.btn_record_output.setObjectName(u"btn_record_output")
        self.btn_record_output.setGeometry(QRect(100, 110, 81, 23))
        self.box_screencap_save_path = QComboBox(self.groupBox_2)
        self.box_screencap_save_path.setObjectName(u"box_screencap_save_path")
        self.box_screencap_save_path.setGeometry(QRect(70, 50, 111, 22))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 54, 21))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 54, 21))
        self.box_display_id = QComboBox(self.groupBox_2)
        self.box_display_id.setObjectName(u"box_display_id")
        self.box_display_id.setGeometry(QRect(70, 20, 51, 22))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"AstrobTestTool", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u4fe1\u606f", None))
        self.btn_refresh.setText(QCoreApplication.translate("MainWindow", u"\u5237\u65b0", None))
        self.label_devices_info.setText(QCoreApplication.translate("MainWindow", u"\u672a\u8fde\u63a5\u8bbe\u5907", None))
        self.btn_connect_device.setText(QCoreApplication.translate("MainWindow", u"\u8fde\u63a5\u8bbe\u5907", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Log\u64cd\u4f5c", None))
        self.btn_log_clear.setText(QCoreApplication.translate("MainWindow", u"\u6e05\u7a7alogcat", None))
        self.box_log_level.setItemText(0, QCoreApplication.translate("MainWindow", u"ERROR", None))
        self.box_log_level.setItemText(1, QCoreApplication.translate("MainWindow", u"WARNING", None))
        self.box_log_level.setItemText(2, QCoreApplication.translate("MainWindow", u"INFO", None))
        self.box_log_level.setItemText(3, QCoreApplication.translate("MainWindow", u"DEBUG", None))

        self.box_log_level.setCurrentText(QCoreApplication.translate("MainWindow", u"ERROR", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"logcat\u7b49\u7ea7", None))
        self.btn_log_start.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u8bb0\u5f55log", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"log\u8bb0\u5f55\u4f4d\u7f6e", None))
        self.btn_log_output.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51falog", None))
        self.btn_log_clear_file.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664log", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u622a\u5c4f\u4e0e\u5f55\u5c4f", None))
        self.btn_screencap.setText(QCoreApplication.translate("MainWindow", u"\u5c4f\u5e55\u622a\u56fe", None))
        self.btn_record_start.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u5f55\u5c4f", None))
        self.btn_screencap_clear_file.setText(QCoreApplication.translate("MainWindow", u"\u6e05\u7406\u8def\u5f84", None))
        self.btn_record_output.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u5f55\u5c4f", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u8def\u5f84", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u5c4f\u5e55\u7f16\u53f7", None))
    # retranslateUi

