ISO_COUNTRY_CODE = {'AND': '安道尔/Andorra',
                    'ARE': '阿联酋/United Arab Emirates',
                    'AFG': '阿富汗/Afghanistan',
                    'ATG': '安提瓜和巴布达/Antigua & Barbuda',
                    'AIA': '安圭拉/Anguilla',
                    'ALB': '阿尔巴尼亚/Albania',
                    'ARM': '亚美尼亚/Armenia',
                    'AGO': '安哥拉/Angola',
                    'ATA': '南极洲/Antarctica',
                    'ARG': '阿根廷/Argentina',
                    'ASM': '美属萨摩亚/American Samoa',
                    'AUT': '奥地利/Austria',
                    'AUS': '澳大利亚/Australia',
                    'ABW': '阿鲁巴/Aruba',
                    'ALA': '奥兰群岛/aland Island',
                    'AZE': '阿塞拜疆/Azerbaijan',
                    'BIH': '波黑/Bosnia & Herzegovina',
                    'BRB': '巴巴多斯/Barbados',
                    'BGD': '孟加拉/Bangladesh',
                    'BEL': '比利时/Belgium',
                    'BFA': '布基纳法索/Burkina',
                    'BGR': '保加利亚/Bulgaria',
                    'BHR': '巴林/Bahrain',
                    'BDI': '布隆迪/Burundi',
                    'BEN': '贝宁/Benin',
                    'BLM': '圣巴泰勒米岛/Saint Barthélemy',
                    'BMU': '百慕大/Bermuda',
                    'BRN': '文莱/Brunei',
                    'BOL': '玻利维亚/Bolivia',
                    'BES': '荷兰加勒比区/Caribbean Netherlands',
                    'BRA': '巴西/Brazil',
                    'BHS': '巴哈马/The Bahamas',
                    'BTN': '不丹/Bhutan',
                    'BVT': '布韦岛/Bouvet Island',
                    'BWA': '博茨瓦纳/Botswana',
                    'BLR': '白俄罗斯/Belarus',
                    'BLZ': '伯利兹/Belize',
                    'CAN': '加拿大/Canada',
                    'CCK': '科科斯群岛/Cocos (Keeling) Islands',
                    'CAF': '中非/Central African Republic',
                    'CHE': '瑞士/Switzerland',
                    'CHL': '智利/Chile',
                    'CMR': '喀麦隆/Cameroon',
                    'COL': '哥伦比亚/Colombia',
                    'CRI': '哥斯达黎加/Costa Rica',
                    'CUB': '古巴/Cuba',
                    'CPV': '佛得角/Cape Verde',
                    'CXR': '圣诞岛/Christmas Island',
                    'CYP': '塞浦路斯/Cyprus',
                    'CZE': '捷克/Czech Republic',
                    'DEU': '德国/Germany',
                    'DJI': '吉布提/Djibouti',
                    'DNK': '丹麦/Denmark',
                    'DMA': '多米尼克/Dominica',
                    'DOM': '多米尼加/Dominican Republic',
                    'DZA': '阿尔及利亚/Algeria',
                    'ECU': '厄瓜多尔/Ecuador',
                    'EST': '爱沙尼亚/Estonia',
                    'EGY': '埃及/Egypt',
                    'ESH': '西撒哈拉/Western Sahara',
                    'ERI': '厄立特里亚/Eritrea',
                    'ESP': '西班牙/Spain',
                    'FIN': '芬兰/Finland',
                    'FJI': '斐济群岛/Fiji',
                    'FLK': '马尔维纳斯群岛（ 福克兰）/Falkland Islands',
                    'FSM': '密克罗尼西亚联邦/Federated States of Micronesia',
                    'FRO': '法罗群岛/Faroe Islands',
                    'FRA': '法国/France',
                    'GAB': '加蓬/Gabon',
                    'GRD': '格林纳达/Grenada',
                    'GEO': '格鲁吉亚/Georgia',
                    'GUF': '法属圭亚那/French Guiana',
                    'GHA': '加纳/Ghana',
                    'GIB': '直布罗陀/Gibraltar',
                    'GRL': '格陵兰/Greenland',
                    'GIN': '几内亚/Guinea',
                    'GLP': '瓜德罗普/Guadeloupe',
                    'GNQ': '赤道几内亚/Equatorial Guinea',
                    'GRC': '希腊/Greece',
                    'SGS': '南乔治亚岛和南桑威奇群岛/South Georgia and the South Sandwich Islands',
                    'GTM': '危地马拉/Guatemala',
                    'GUM': '关岛/Guam',
                    'GNB': '几内亚比绍/Guinea-Bissau',
                    'GUY': '圭亚那/Guyana',
                    'HKG': '香港/Hong Kong',
                    'HMD': '赫德岛和麦克唐纳群岛/Heard Island and McDonald Islands',
                    'HND': '洪都拉斯/Honduras',
                    'HRV': '克罗地亚/Croatia',
                    'HTI': '海地/Haiti',
                    'HUN': '匈牙利/Hungary',
                    'IDN': '印尼/Indonesia',
                    'IRL': '爱尔兰/Ireland',
                    'ISR': '以色列/Israel',
                    'IMN': '马恩岛/Isle of Man',
                    'IND': '印度/India',
                    'IOT': '英属印度洋领地/British Indian Ocean Territory',
                    'IRQ': '伊拉克/Iraq',
                    'IRN': '伊朗/Iran',
                    'ISL': '冰岛/Iceland',
                    'ITA': '意大利/Italy',
                    'JEY': '泽西岛/Jersey',
                    'JAM': '牙买加/Jamaica',
                    'JOR': '约旦/Jordan',
                    'JPN': '日本/Japan',
                    'KHM': '柬埔寨/Cambodia',
                    'KIR': '基里巴斯/Kiribati',
                    'COM': '科摩罗/The Comoros',
                    'KWT': '科威特/Kuwait',
                    'CYM': '开曼群岛/Cayman Islands',
                    'LBN': '黎巴嫩/Lebanon',
                    'LIE': '列支敦士登/Liechtenstein',
                    'LKA': '斯里兰卡/Sri Lanka',
                    'LBR': '利比里亚/Liberia',
                    'LSO': '莱索托/Lesotho',
                    'LTU': '立陶宛/Lithuania',
                    'LUX': '卢森堡/Luxembourg',
                    'LVA': '拉脱维亚/Latvia',
                    'LBY': '利比亚/Libya',
                    'MAR': '摩洛哥/Morocco',
                    'MCO': '摩纳哥/Monaco',
                    'MDA': '摩尔多瓦/Moldova',
                    'MNE': '黑山/Montenegro',
                    'MAF': '法属圣马丁/Saint Martin (France)',
                    'MDG': '马达加斯加/Madagascar',
                    'MHL': '马绍尔群岛/Marshall islands',
                    'MKD': '马其顿/Republic of Macedonia (FYROM)',
                    'MLI': '马里/Mali',
                    'MMR': '缅甸/Myanmar (Burma)',
                    'MAC': '澳门/Macao',
                    'MTQ': '马提尼克/Martinique',
                    'MRT': '毛里塔尼亚/Mauritania',
                    'MSR': '蒙塞拉特岛/Montserrat',
                    'MLT': '马耳他/Malta',
                    'MDV': '马尔代夫/Maldives',
                    'MWI': '马拉维/Malawi',
                    'MEX': '墨西哥/Mexico',
                    'MYS': '马来西亚/Malaysia',
                    'NAM': '纳米比亚/Namibia',
                    'NER': '尼日尔/Niger',
                    'NFK': '诺福克岛/Norfolk Island',
                    'NGA': '尼日利亚/Nigeria',
                    'NIC': '尼加拉瓜/Nicaragua',
                    'NLD': '荷兰/Netherlands',
                    'NOR': '挪威/Norway',
                    'NPL': '尼泊尔/Nepal',
                    'NRU': '瑙鲁/Nauru',
                    'OMN': '阿曼/Oman',
                    'PAN': '巴拿马/Panama',
                    'PER': '秘鲁/Peru',
                    'PYF': '法属波利尼西亚/French polynesia',
                    'PNG': '巴布亚新几内亚/Papua New Guinea',
                    'PHL': '菲律宾/The Philippines',
                    'PAK': '巴基斯坦/Pakistan',
                    'POL': '波兰/Poland',
                    'PCN': '皮特凯恩群岛/Pitcairn Islands',
                    'PRI': '波多黎各/Puerto Rico',
                    'PSE': '巴勒斯坦/Palestinian territories',
                    'PLW': '帕劳/Palau',
                    'PRY': '巴拉圭/Paraguay',
                    'QAT': '卡塔尔/Qatar',
                    'REU': '留尼汪/Réunion',
                    'ROU': '罗马尼亚/Romania',
                    'SRB': '塞尔维亚/Serbia',
                    'RUS': '俄罗斯/Russian Federation',
                    'RWA': '卢旺达/Rwanda',
                    'SLB': '所罗门群岛/Solomon Islands',
                    'SYC': '塞舌尔/Seychelles',
                    'SDN': '苏丹/Sudan',
                    'SWE': '瑞典/Sweden',
                    'SGP': '新加坡/Singapore',
                    'SVN': '斯洛文尼亚/Slovenia',
                    'SJM': '斯瓦尔巴群岛和 扬马延岛/Template:Country data SJM Svalbard',
                    'SVK': '斯洛伐克/Slovakia',
                    'SLE': '塞拉利昂/Sierra Leone',
                    'SMR': '圣马力诺/San Marino',
                    'SEN': '塞内加尔/Senegal',
                    'SOM': '索马里/Somalia',
                    'SUR': '苏里南/Suriname',
                    'SSD': '南苏丹/South Sudan',
                    'STP': '圣多美和普林西比/Sao Tome & Principe',
                    'SLV': '萨尔瓦多/El Salvador',
                    'SYR': '叙利亚/Syria',
                    'SWZ': '斯威士兰/Swaziland',
                    'TCA': '特克斯和凯科斯群岛/Turks & Caicos Islands',
                    'TCD': '乍得/Chad',
                    'TGO': '多哥/Togo',
                    'THA': '泰国/Thailand',
                    'TKL': '托克劳/Tokelau',
                    'TLS': '东帝汶/Timor-Leste (East Timor)',
                    'TUN': '突尼斯/Tunisia',
                    'TON': '汤加/Tonga',
                    'TUR': '土耳其/Turkey',
                    'TUV': '图瓦卢/Tuvalu',
                    'TZA': '坦桑尼亚/Tanzania',
                    'UKR': '乌克兰/Ukraine',
                    'UGA': '乌干达/Uganda',
                    'USA': '美国/United States of America (USA)',
                    'URY': '乌拉圭/Uruguay',
                    'VAT': '梵蒂冈/Vatican City (The Holy See)',
                    'VEN': '委内瑞拉/Venezuela',
                    'VGB': '英属维尔京群岛/British Virgin Islands',
                    'VIR': '美属维尔京群岛/United States Virgin Islands',
                    'VNM': '越南/Vietnam',
                    'WLF': '瓦利斯和富图纳/Wallis and Futuna',
                    'WSM': '萨摩亚/Samoa',
                    'YEM': '也门/Yemen',
                    'MYT': '马约特/Mayotte',
                    'ZAF': '南非/South Africa',
                    'ZMB': '赞比亚/Zambia',
                    'ZWE': '津巴布韦/Zimbabwe',
                    'CHN': '中国 内地/China',
                    'COG': '刚果（布）/Republic of the Congo',
                    'COD': '刚果（金）/Democratic Republic of the Congo',
                    'MOZ': '莫桑比克/Mozambique',
                    'GGY': '根西岛/Guernsey',
                    'GMB': '冈比亚/Gambia',
                    'MNP': '北马里亚纳群岛/Northern Mariana Islands',
                    'ETH': '埃塞俄比亚/Ethiopia',
                    'NCL': '新喀里多尼亚/New Caledonia',
                    'VUT': '瓦努阿图/Vanuatu',
                    'ATF': '法属南部领地/French Southern Territories',
                    'NIU': '纽埃/Niue',
                    'UMI': '美国本土外小岛屿/United States Minor Outlying Islands',
                    'COK': '库克群岛/Cook Islands',
                    'GBR': '英国/Great Britain (United Kingdom; England)',
                    'TTO': '特立尼达和多巴哥/Trinidad & Tobago',
                    'VCT': '圣文森特和格林纳丁斯/St. Vincent & the Grenadines',
                    'TWN': '中华民国（台湾）/Taiwan',
                    'NZL': '新西兰/New Zealand',
                    'SAU': '沙特阿拉伯/Saudi Arabia',
                    'LAO': '老挝/Laos',
                    'PRK': '朝鲜(北朝鲜)/North Korea',
                    'KOR': '韩国(南朝鲜)/South Korea',
                    'PRT': '葡萄牙/Portugal',
                    'KGZ': '吉尔吉斯斯坦/Kyrgyzstan',
                    'KAZ': '哈萨克斯坦/Kazakhstan',
                    'TJK': '塔吉克斯坦/Tajikistan',
                    'TKM': '土库曼斯坦/Turkmenistan',
                    'UZB': '乌兹别克斯坦/Uzbekistan',
                    'KNA': '圣基茨和尼维斯/St. Kitts & Nevis',
                    'SPM': '圣皮埃尔和密克隆/Saint-Pierre and Miquelon',
                    'SHN': '圣赫勒拿/St. Helena & Dependencies',
                    'LCA': '圣卢西亚/St. Lucia',
                    'MUS': '毛里求斯/Mauritius',
                    'CIV': "科特迪瓦/Cote d'Ivoire",
                    'KEN': '肯尼亚/Kenya',
                    'MNG': '蒙古国 蒙古/Mongolia'}
